### PR TITLE
fixed type=daily for provider openmeteo showing nightly icons

### LINKED ISSUE #3458: [weather] provider openmeteo showing nightly icons in forecast when current time is "nightly"
current:

grafik

expected:

grafik

will fix this ...

### PR DESCRIPTION
**Pull request by khassel**
in forecast when current time is "nightly"

Fixes #3458

### CODE REVIEW

File: modules/default/weather/providers/openmeteo.js [hunk 1]
```diff
@@ -401,7 +401,7 @@ WeatherProvider.register("openmeteo", {
 			currentWeather.temperature = parseFloat((weather.apparent_temperature_max + weather.apparent_temperature_min) / 2);
 			currentWeather.minTemperature = parseFloat(weather.apparent_temperature_min);
 			currentWeather.maxTemperature = parseFloat(weather.apparent_temperature_max);
-			currentWeather.weatherType = this.convertWeatherType(weather.weathercode, currentWeather.isDayTime());
+			currentWeather.weatherType = this.convertWeatherType(weather.weathercode, true);
```
Comment (rejas) [inline modules/default/weather/providers/openmeteo.js:404]: how would this show night icons when the isDayTime is now always true?

Comment (khassel) [reply modules/default/weather/providers/openmeteo.js:404]: this will never show night icons and this is intended. Using the function `isDayTime` is o.k. for current and hourly but I never want to see night icons in a daily forecast. Did you see the pictures in the issue?

Comment (rejas) [reply modules/default/weather/providers/openmeteo.js:404]: Doh!!! Makes perfect sense!

**Review by rejas — APPROVED** [review]
